update to v0.5 (#53)

diff --git a/bin/reset-env b/bin/reset-env
--- a/bin/reset-env
+++ b/bin/reset-env
@@ -7,3 +7,14 @@ bin/console doctrine:database:drop --force  && \
 bin/console doctrine:database:create && \
 bin/console doctrine:schema:update --force && \
 bin/console doctrine:fixtures:load -n
+[[ $? -ne 0 ]] && echo "Environment setup failed" && exit 1
+
+if [[ -f .env ]] ; then
+    source .env
+fi
+
+if [[ ! -z $ELASTICSEARCH_HOST ]] ; then
+    bin/console projection:initialize-types --force && \
+    bin/console projection:synchronize
+    [[ $? -ne 0 ]] && echo "Projection synchronization failed" && exit 1
+fi
