generate jwt

diff --git a/bin/reset-env b/bin/reset-env
--- a/bin/reset-env
+++ b/bin/reset-env
@@ -7,8 +7,16 @@ bin/console doctrine:schema:update --force && \
 bin/console doctrine:fixtures:load -n
 [[ $? -ne 0 ]] && echo "Environment setup failed" && exit 1
 
+source .env.dist .env .env.local
+
 if [[ ! -z $ELASTICSEARCH_HOST ]] ; then
     bin/console projection:initialize-types --force && \
     bin/console projection:synchronize
-    [[ $? -ne 0 ]] && echo "Projection synchronization failed" && exit 1
+    [[ $? -ne 0 ]] && echo "Projection synchronization failed"
+fi
+
+if [[ ! -f config/jwt/private.pem || ! -f config/jwt/public.pem ]] ; then
+    openssl genrsa -out config/jwt/private.pem -aes256 4096 && \
+    openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
+    [[ $? -ne 0 ]] && echo "JWT generation failed"
 fi
